// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzo08Tdncxb2P01TEHQDEXCFEh3z6dzW4',
    appId: '1:1096749386222:web:313bb9db1c5f7b56cd26ff',
    messagingSenderId: '1096749386222',
    projectId: 'college-coding-culture',
    authDomain: 'college-coding-culture.firebaseapp.com',
    storageBucket: 'college-coding-culture.firebasestorage.app',
    measurementId: 'G-PTXJQE14N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6EXoDhFod5oAcWWgzRCrIckvjCMfLcFk',
    appId: '1:1096749386222:android:83883223b3d583b1cd26ff',
    messagingSenderId: '1096749386222',
    projectId: 'college-coding-culture',
    storageBucket: 'college-coding-culture.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq3hExUgJfAgtD_gsd52qIfC37yBSufto',
    appId: '1:1096749386222:ios:3a86fcd7ee81b002cd26ff',
    messagingSenderId: '1096749386222',
    projectId: 'college-coding-culture',
    storageBucket: 'college-coding-culture.firebasestorage.app',
    iosBundleId: 'com.example.ccc',
  );
}